<<<<<<< HEAD
services:
  music_bot:
    build: .
    container_name: music_bot
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - sqlite_db

  sqlite_db:
    image: nouchka/sqlite3
    container_name: sqlite_db
    stdin_open: true
    tty: true
=======
services:
  music_bot:
    build: .
    container_name: music_bot
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - sqlite_db

  sqlite_db:
    image: nouchka/sqlite3
    container_name: sqlite_db
    stdin_open: true
    tty: true
>>>>>>> 5852130ac5d032ece869f1de256e3f764e45de32
